// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Data;

#nullable disable

namespace NZWalks.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241107155433_SeededDifficultyDataWithoutController")]
    partial class SeededDifficultyDataWithoutController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d043934d-3481-48df-860a-e8199e9aa923"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("6c1366bd-7194-4450-b22b-63ad8420d137"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("1c900f7f-82be-4ea7-8908-1a748fc5bcae"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d043934d-3481-48df-860a-e8199e9aa923"),
                            Code = "FL",
                            Name = "Florida",
                            RegionImageUrl = "https://dummyimage.com/400x400/000/fff.png"
                        },
                        new
                        {
                            Id = new Guid("b123f4de-5678-90ab-cdef-111213141516"),
                            Code = "CA",
                            Name = "California",
                            RegionImageUrl = "https://dummyimage.com/400x400/ff0000/fff.png"
                        },
                        new
                        {
                            Id = new Guid("c67890ab-1234-56de-7890-123456789012"),
                            Code = "NY",
                            Name = "New York",
                            RegionImageUrl = "https://dummyimage.com/400x400/00ff00/fff.png"
                        },
                        new
                        {
                            Id = new Guid("d7890123-4567-89ab-cdef-098765432123"),
                            Code = "TX",
                            Name = "Texas",
                            RegionImageUrl = "https://dummyimage.com/400x400/0000ff/fff.png"
                        },
                        new
                        {
                            Id = new Guid("e0123456-7890-12ab-cdef-123456789abc"),
                            Code = "WA",
                            Name = "Washington",
                            RegionImageUrl = "https://dummyimage.com/400x400/ffff00/000.png"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImamgeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");
                });
#pragma warning restore 612, 618
        }
    }
}
